export const defaultImages = [
    {
        id: "EitiaUwmD-8",
        alternative_slugs: {
            en: "louvre-museum-at-paris-france-EitiaUwmD-8",
            es: "museo-del-louvre-en-paris-francia-EitiaUwmD-8",
            ja: "フランスパリのルーヴル美術館-EitiaUwmD-8",
            fr: "musee-du-louvre-a-paris-france-EitiaUwmD-8",
            it: "museo-del-louvre-a-parigi-francia-EitiaUwmD-8",
            ko: "프랑스-파리-루브르-박물관-EitiaUwmD-8",
            de: "louvre-museum-in-paris-frankreich-EitiaUwmD-8",
            pt: "museu-do-louvre-em-paris-franca-EitiaUwmD-8",
            id: "museum-louvre-di-paris-prancis-EitiaUwmD-8",
        },
        created_at: "2018-11-27T16:23:17Z",
        updated_at: "2026-08-10T05:01:30Z",
        promoted_at: "2018-11-28T08:29:03Z",
        width: 3840,
        height: 2160,
        color: "#0c2640",
        blur_hash: "LA7-Z+Rj9Fof0Jof%2WBITay%2ay",
        description: "14mm (28mm FF), bracketing with long and short exposure",
        breadcrumbs: [],
        urls: {
            raw: "https://images.unsplash.com/photo-1543335785-8aadf6d8183c?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0",
            full: "https://images.unsplash.com/photo-1543335785-8aadf6d8183c?crop=entropy&cs=srgb&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=85",
            regular:
                "https://images.unsplash.com/photo-1543335785-8aadf6d8183c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=1080",
            small: "https://images.unsplash.com/photo-1543335785-8aadf6d8183c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=400",
            thumb: "https://images.unsplash.com/photo-1543335785-8aadf6d8183c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=200",
            small_s3:
                "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1543335785-8aadf6d8183c",
        },
        likes: 1028,
        liked_by_user: false,
        bookmarked: false,
        current_user_collections: [],
        sponsorship: null,
        topic_submissions: {},
        asset_type: "photo",
        slug: "louvre-museum-at-paris-france-EitiaUwmD-8",
        alt_description: "Louvre Museum at Paris France",
        links: {
            self: "https://api.unsplash.com/photos/louvre-museum-at-paris-france-EitiaUwmD-8",
            html: "https://unsplash.com/photos/louvre-museum-at-paris-france-EitiaUwmD-8",
            download:
                "https://unsplash.com/photos/EitiaUwmD-8/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
            download_location:
                "https://api.unsplash.com/photos/EitiaUwmD-8/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
        },
        user: {
            id: "JYbx7vUXl-Q",
            updated_at: "2026-07-10T14:00:04Z",
            username: "jvenerosy",
            name: "J Venerosy",
            first_name: "J",
            last_name: "Venerosy",
            twitter_username: "jvenerosy",
            portfolio_url: null,
            bio: null,
            location: "Paris",
            links: {
                self: "https://api.unsplash.com/users/jvenerosy",
                photos: "https://api.unsplash.com/users/jvenerosy/photos",
                likes: "https://api.unsplash.com/users/jvenerosy/likes",
                html: "https://unsplash.com/@jvenerosy",
            },
            profile_image: {
                small: "https://images.unsplash.com/placeholder-avatars/extra-large.jpg?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
                medium: "https://images.unsplash.com/placeholder-avatars/extra-large.jpg?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
                large: "https://images.unsplash.com/placeholder-avatars/extra-large.jpg?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
            },
            instagram_username: "jvenerosy",
            total_collections: 6,
            total_likes: 8,
            total_photos: 5,
            total_free_photos: 5,
            total_promoted_photos: 1,
            total_illustrations: 0,
            total_free_illustrations: 0,
            total_promoted_illustrations: 0,
            accepted_tos: true,
            for_hire: true,
            social: {
                instagram_username: "jvenerosy",
                portfolio_url: null,
                twitter_username: "jvenerosy",
                paypal_email: null,
            },
        },
        exif: {
            make: "Panasonic",
            model: "Lumix G7",
            name: "Panasonic, Lumix G7",
            exposure_time: "1/3",
            aperture: "3",
            focal_length: "14",
            iso: 200,
        },
        location: {
            name: "Pyramide du Louvres, Paris, France",
            city: "Paris",
            country: "France",
            position: {
                latitude: null,
                longitude: null,
            },
        },
        views: 16102845,
        downloads: 20679,
    },
    {
        id: "xzqoCCw1ZvI",
        alternative_slugs: {
            en: "brown-woods-xzqoCCw1ZvI",
            es: "maderas-marrones-xzqoCCw1ZvI",
            ja: "ブラウンウッズ-xzqoCCw1ZvI",
            fr: "bois-bruns-xzqoCCw1ZvI",
            it: "legni-marroni-xzqoCCw1ZvI",
            ko: "브라운-우즈-xzqoCCw1ZvI",
            de: "braune-holzer-xzqoCCw1ZvI",
            pt: "madeiras-marrons-xzqoCCw1ZvI",
            id: "kayu-coklat-xzqoCCw1ZvI",
        },
        created_at: "2018-12-04T00:42:43Z",
        updated_at: "2026-08-10T00:08:58Z",
        promoted_at: "2018-12-04T09:52:13Z",
        width: 5760,
        height: 3840,
        color: "#f3f3f3",
        blur_hash: "LRPGdI4Txux]-:_3x]Rj-=x]IUWA",
        description: "Possibilities",
        breadcrumbs: [],
        urls: {
            raw: "https://images.unsplash.com/photo-1543884147-98850deeacb2?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0",
            full: "https://images.unsplash.com/photo-1543884147-98850deeacb2?crop=entropy&cs=srgb&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=85",
            regular:
                "https://images.unsplash.com/photo-1543884147-98850deeacb2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=1080",
            small: "https://images.unsplash.com/photo-1543884147-98850deeacb2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=400",
            thumb: "https://images.unsplash.com/photo-1543884147-98850deeacb2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=200",
            small_s3:
                "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1543884147-98850deeacb2",
        },
        likes: 178,
        liked_by_user: false,
        bookmarked: false,
        current_user_collections: [],
        sponsorship: null,
        topic_submissions: {},
        asset_type: "photo",
        slug: "brown-woods-xzqoCCw1ZvI",
        alt_description: "brown woods",
        links: {
            self: "https://api.unsplash.com/photos/brown-woods-xzqoCCw1ZvI",
            html: "https://unsplash.com/photos/brown-woods-xzqoCCw1ZvI",
            download:
                "https://unsplash.com/photos/xzqoCCw1ZvI/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
            download_location:
                "https://api.unsplash.com/photos/xzqoCCw1ZvI/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
        },
        user: {
            id: "uMJXuywXLiU",
            updated_at: "2026-08-06T00:12:48Z",
            username: "iamthedave",
            name: "Dave Hoefler",
            first_name: "Dave",
            last_name: "Hoefler",
            twitter_username: null,
            portfolio_url: null,
            bio: "I like nature.",
            location: null,
            links: {
                self: "https://api.unsplash.com/users/iamthedave",
                photos: "https://api.unsplash.com/users/iamthedave/photos",
                likes: "https://api.unsplash.com/users/iamthedave/likes",
                html: "https://unsplash.com/@iamthedave",
            },
            profile_image: {
                small: "https://images.unsplash.com/profile-1728755589926-78ac077e87a6image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
                medium: "https://images.unsplash.com/profile-1728755589926-78ac077e87a6image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
                large: "https://images.unsplash.com/profile-1728755589926-78ac077e87a6image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
            },
            instagram_username: null,
            total_collections: 0,
            total_likes: 162,
            total_photos: 1027,
            total_free_photos: 1027,
            total_promoted_photos: 435,
            total_illustrations: 0,
            total_free_illustrations: 0,
            total_promoted_illustrations: 0,
            accepted_tos: true,
            for_hire: true,
            social: {
                instagram_username: null,
                portfolio_url: null,
                twitter_username: null,
                paypal_email: null,
            },
        },
        exif: {
            make: "Canon",
            model: "Canon EOS 5D Mark III",
            name: "Canon, EOS 5D Mark III",
            exposure_time: "210",
            aperture: "10.0",
            focal_length: "135.0",
            iso: 400,
        },
        location: {
            name: "Astoria, US",
            city: "Astoria",
            country: "US",
            position: {
                latitude: null,
                longitude: null,
            },
        },
        views: 9291548,
        downloads: 9456,
    },
    {
        id: "qi2-ePRjgGw",
        alternative_slugs: {
            en: "a-dark-forest-silhouette-under-a-starry-night-sky-qi2-ePRjgGw",
            es: "una-silueta-oscura-de-bosque-bajo-un-cielo-estrellado-qi2-ePRjgGw",
            ja: "星空の下暗い森のシルエット-qi2-ePRjgGw",
            fr: "une-silhouette-sombre-de-foret-sous-un-ciel-etoile-qi2-ePRjgGw",
            it: "una-sagoma-di-foresta-scura-sotto-un-cielo-stellato-qi2-ePRjgGw",
            ko: "별이-빛나는-밤하늘-아래-어두운-숲의-실루엣-qi2-ePRjgGw",
            de: "eine-dunkle-waldsilhouette-unter-einem-sternenklaren-nachthimmel-qi2-ePRjgGw",
            pt: "uma-silhueta-de-floresta-escura-sob-um-ceu-noturno-estrelado-qi2-ePRjgGw",
            id: "siluet-hutan-gelap-di-bawah-langit-malam-berbintang-qi2-ePRjgGw",
        },
        created_at: "2026-04-16T09:56:51Z",
        updated_at: "2026-08-10T03:41:58Z",
        promoted_at: "2026-04-17T00:38:00Z",
        width: 4598,
        height: 3065,
        color: "#262640",
        blur_hash: "L42Fffj^R$jtkGaxfOaxIQawoga{",
        description: null,
        breadcrumbs: [],
        urls: {
            raw: "https://images.unsplash.com/photo-1776333181065-fe91f63d17eb?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0",
            full: "https://images.unsplash.com/photo-1776333181065-fe91f63d17eb?crop=entropy&cs=srgb&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=85",
            regular:
                "https://images.unsplash.com/photo-1776333181065-fe91f63d17eb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=1080",
            small: "https://images.unsplash.com/photo-1776333181065-fe91f63d17eb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=400",
            thumb: "https://images.unsplash.com/photo-1776333181065-fe91f63d17eb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=200",
            small_s3:
                "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1776333181065-fe91f63d17eb",
        },
        likes: 18,
        liked_by_user: false,
        bookmarked: false,
        current_user_collections: [],
        sponsorship: null,
        topic_submissions: {
            nature: {
                status: "approved",
                approved_on: "2026-04-17T13:31:13Z",
            },
        },
        asset_type: "photo",
        slug: "a-dark-forest-silhouette-under-a-starry-night-sky-qi2-ePRjgGw",
        alt_description: "A dark forest silhouette under a starry night sky",
        links: {
            self: "https://api.unsplash.com/photos/a-dark-forest-silhouette-under-a-starry-night-sky-qi2-ePRjgGw",
            html: "https://unsplash.com/photos/a-dark-forest-silhouette-under-a-starry-night-sky-qi2-ePRjgGw",
            download:
                "https://unsplash.com/photos/qi2-ePRjgGw/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
            download_location:
                "https://api.unsplash.com/photos/qi2-ePRjgGw/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
        },
        user: {
            id: "ItujYYI9BdM",
            updated_at: "2026-08-06T10:33:16Z",
            username: "greensyntax",
            name: "Abhishek Ravi",
            first_name: "Abhishek",
            last_name: "Ravi",
            twitter_username: null,
            portfolio_url: null,
            bio: '"Tu Koi aur hai"',
            location: "India",
            links: {
                self: "https://api.unsplash.com/users/greensyntax",
                photos: "https://api.unsplash.com/users/greensyntax/photos",
                likes: "https://api.unsplash.com/users/greensyntax/likes",
                html: "https://unsplash.com/@greensyntax",
            },
            profile_image: {
                small: "https://images.unsplash.com/profile-1775997716285-2d3d55be245aimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
                medium: "https://images.unsplash.com/profile-1775997716285-2d3d55be245aimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
                large: "https://images.unsplash.com/profile-1775997716285-2d3d55be245aimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
            },
            instagram_username: "abhishekravi.jpeg",
            total_collections: 0,
            total_likes: 1,
            total_photos: 64,
            total_free_photos: 64,
            total_promoted_photos: 1,
            total_illustrations: 0,
            total_free_illustrations: 0,
            total_promoted_illustrations: 0,
            accepted_tos: true,
            for_hire: true,
            social: {
                instagram_username: "abhishekravi.jpeg",
                portfolio_url: null,
                twitter_username: null,
                paypal_email: null,
            },
        },
        exif: {
            make: "SONY",
            model: "ILCE-7M3",
            name: "SONY, ILCE-7M3",
            exposure_time: "30",
            aperture: "4.0",
            focal_length: "20.0",
            iso: 160,
        },
        location: {
            name: "Chopta Valley, Green Valley, Uttarakhand",
            city: "Green Valley",
            country: "India",
            position: {
                latitude: 30.487617,
                longitude: 79.209295,
            },
        },
        views: 10099224,
        downloads: 42700,
    },
    {
        id: "EiczCEMs244",
        alternative_slugs: {
            en: "a-single-orange-flower-in-a-field-of-blue-flowers-EiczCEMs244",
            es: "una-sola-flor-de-naranjo-en-un-campo-de-flores-azules-EiczCEMs244",
            ja: "青い花畑に一輪のオレンジ色の花-EiczCEMs244",
            fr: "une-seule-fleur-doranger-dans-un-champ-de-fleurs-bleues-EiczCEMs244",
            it: "un-singolo-fiore-arancione-in-un-campo-di-fiori-blu-EiczCEMs244",
            ko: "푸른-꽃밭에-오렌지-꽃-한-송이-EiczCEMs244",
            de: "eine-einzelne-orangefarbene-blume-in-einem-feld-mit-blauen-blumen-EiczCEMs244",
            pt: "uma-unica-flor-laranja-em-um-campo-de-flores-azuis-EiczCEMs244",
            id: "satu-bunga-oranye-di-ladang-bunga-biru-EiczCEMs244",
        },
        created_at: "2024-06-02T09:43:21Z",
        updated_at: "2026-08-10T00:07:18Z",
        promoted_at: "2024-06-04T08:28:12Z",
        width: 2304,
        height: 3072,
        color: "#c0d9f3",
        blur_hash: "L9KfErE3?ct8Pqt8D%V?4=Rkt6bc",
        description: null,
        breadcrumbs: [],
        urls: {
            raw: "https://images.unsplash.com/photo-1717320864441-493a511a822a?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0",
            full: "https://images.unsplash.com/photo-1717320864441-493a511a822a?crop=entropy&cs=srgb&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=85",
            regular:
                "https://images.unsplash.com/photo-1717320864441-493a511a822a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=1080",
            small: "https://images.unsplash.com/photo-1717320864441-493a511a822a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=400",
            thumb: "https://images.unsplash.com/photo-1717320864441-493a511a822a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=200",
            small_s3:
                "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1717320864441-493a511a822a",
        },
        likes: 184,
        liked_by_user: false,
        bookmarked: false,
        current_user_collections: [],
        sponsorship: null,
        topic_submissions: {
            pastels: {
                status: "approved",
                approved_on: "2024-06-10T14:04:49Z",
            },
            nature: {
                status: "rejected",
            },
        },
        asset_type: "photo",
        slug: "a-single-orange-flower-in-a-field-of-blue-flowers-EiczCEMs244",
        alt_description: "a single orange flower in a field of blue flowers",
        links: {
            self: "https://api.unsplash.com/photos/a-single-orange-flower-in-a-field-of-blue-flowers-EiczCEMs244",
            html: "https://unsplash.com/photos/a-single-orange-flower-in-a-field-of-blue-flowers-EiczCEMs244",
            download:
                "https://unsplash.com/photos/EiczCEMs244/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
            download_location:
                "https://api.unsplash.com/photos/EiczCEMs244/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
        },
        user: {
            id: "vckKL36bIlo",
            updated_at: "2026-07-30T15:06:09Z",
            username: "eysmanpics",
            name: "YUNAN WANG",
            first_name: "YUNAN",
            last_name: "WANG",
            twitter_username: null,
            portfolio_url: null,
            bio: null,
            location: "tokyo",
            links: {
                self: "https://api.unsplash.com/users/eysmanpics",
                photos: "https://api.unsplash.com/users/eysmanpics/photos",
                likes: "https://api.unsplash.com/users/eysmanpics/likes",
                html: "https://unsplash.com/@eysmanpics",
            },
            profile_image: {
                small: "https://images.unsplash.com/profile-1712579488151-bbe60f068d44image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
                medium: "https://images.unsplash.com/profile-1712579488151-bbe60f068d44image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
                large: "https://images.unsplash.com/profile-1712579488151-bbe60f068d44image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
            },
            instagram_username: "eyesman_studio",
            total_collections: 1,
            total_likes: 0,
            total_photos: 91,
            total_free_photos: 91,
            total_promoted_photos: 7,
            total_illustrations: 0,
            total_free_illustrations: 0,
            total_promoted_illustrations: 0,
            accepted_tos: true,
            for_hire: true,
            social: {
                instagram_username: "eyesman_studio",
                portfolio_url: null,
                twitter_username: null,
                paypal_email: null,
            },
        },
        exif: {
            make: null,
            model: null,
            name: null,
            exposure_time: null,
            aperture: null,
            focal_length: null,
            iso: null,
        },
        location: {
            name: "Hitachi Seaside Park, Mawatari, Hitachinaka, Ibaraki, Japan",
            city: "Hitachinaka",
            country: "Japan",
            position: {
                latitude: 36.405864,
                longitude: 140.596487,
            },
        },
        views: 8894694,
        downloads: 136163,
    },
    {
        id: "Nus6XsBNRPY",
        alternative_slugs: {
            en: "brown-and-white-mountains-under-white-clouds-during-daytime-Nus6XsBNRPY",
            es: "montanas-marrones-y-blancas-bajo-nubes-blancas-durante-el-dia-Nus6XsBNRPY",
            ja: "昼間の白い雲の下の茶色と白の山々-Nus6XsBNRPY",
            fr: "montagnes-brunes-et-blanches-sous-des-nuages-blancs-pendant-la-journee-Nus6XsBNRPY",
            it: "montagne-marroni-e-bianche-sotto-nuvole-bianche-durante-il-giorno-Nus6XsBNRPY",
            ko: "낮에는-흰-구름-아래-갈색과-흰색-산-Nus6XsBNRPY",
            de: "braune-und-weisse-berge-unter-weissen-wolken-tagsuber-Nus6XsBNRPY",
            pt: "montanhas-marrons-e-brancas-sob-nuvens-brancas-durante-o-dia-Nus6XsBNRPY",
            id: "pegunungan-coklat-dan-putih-di-bawah-awan-putih-pada-siang-hari-Nus6XsBNRPY",
        },
        created_at: "2020-09-15T00:05:26Z",
        updated_at: "2026-08-10T01:31:49Z",
        promoted_at: "2020-09-15T14:54:03Z",
        width: 4000,
        height: 6000,
        color: "#8c8ca6",
        blur_hash: "LPFYfXt7j?oKyZj[o0az9FjZWXj[",
        description: "A smoky day in the Rockies. ",
        breadcrumbs: [],
        urls: {
            raw: "https://images.unsplash.com/photo-1600128224879-2a06a3639e95?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0",
            full: "https://images.unsplash.com/photo-1600128224879-2a06a3639e95?crop=entropy&cs=srgb&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=85",
            regular:
                "https://images.unsplash.com/photo-1600128224879-2a06a3639e95?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=1080",
            small: "https://images.unsplash.com/photo-1600128224879-2a06a3639e95?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=400",
            thumb: "https://images.unsplash.com/photo-1600128224879-2a06a3639e95?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=200",
            small_s3:
                "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1600128224879-2a06a3639e95",
        },
        likes: 124,
        liked_by_user: false,
        bookmarked: false,
        current_user_collections: [],
        sponsorship: null,
        topic_submissions: {
            nature: {
                status: "rejected",
            },
        },
        asset_type: "photo",
        slug: "brown-and-white-mountains-under-white-clouds-during-daytime-Nus6XsBNRPY",
        alt_description: "brown and white mountains under white clouds during daytime",
        links: {
            self: "https://api.unsplash.com/photos/brown-and-white-mountains-under-white-clouds-during-daytime-Nus6XsBNRPY",
            html: "https://unsplash.com/photos/brown-and-white-mountains-under-white-clouds-during-daytime-Nus6XsBNRPY",
            download:
                "https://unsplash.com/photos/Nus6XsBNRPY/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
            download_location:
                "https://api.unsplash.com/photos/Nus6XsBNRPY/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
        },
        user: {
            id: "KubfMUMlN7g",
            updated_at: "2026-07-10T14:01:15Z",
            username: "haleytruong",
            name: "Haley Truong",
            first_name: "Haley",
            last_name: "Truong",
            twitter_username: null,
            portfolio_url: "http://haleytruong.com",
            bio: "Capturing moments from all around me. \r\nThank you for 35 mil+ views and 170k+ downloads!     I appreciate any support! https://www.buymeacoffee.com/haleytruong",
            location: "Canada",
            links: {
                self: "https://api.unsplash.com/users/haleytruong",
                photos: "https://api.unsplash.com/users/haleytruong/photos",
                likes: "https://api.unsplash.com/users/haleytruong/likes",
                html: "https://unsplash.com/@haleytruong",
            },
            profile_image: {
                small: "https://images.unsplash.com/profile-fb-1557867338-3d193cf65674.jpg?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
                medium: "https://images.unsplash.com/profile-fb-1557867338-3d193cf65674.jpg?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
                large: "https://images.unsplash.com/profile-fb-1557867338-3d193cf65674.jpg?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
            },
            instagram_username: "haley.truong",
            total_collections: 3,
            total_likes: 38,
            total_photos: 109,
            total_free_photos: 109,
            total_promoted_photos: 14,
            total_illustrations: 0,
            total_free_illustrations: 0,
            total_promoted_illustrations: 0,
            accepted_tos: true,
            for_hire: true,
            social: {
                instagram_username: "haley.truong",
                portfolio_url: "http://haleytruong.com",
                twitter_username: null,
                paypal_email: null,
            },
        },
        exif: {
            make: "SONY",
            model: "ILCE-6000",
            name: "SONY, ILCE-6000",
            exposure_time: "1/4000",
            aperture: "1.4",
            focal_length: "16.0",
            iso: 100,
        },
        location: {
            name: "Kananaskis, AB, Canada",
            city: "Kananaskis",
            country: "Canada",
            position: {
                latitude: 51.076336,
                longitude: -115.1288,
            },
        },
        views: 10268256,
        downloads: 27825,
    },
    {
        id: "zXQbf1pyZpo",
        alternative_slugs: {
            en: "selective-focus-photography-of-splash-of-water-zXQbf1pyZpo",
            es: "fotografia-de-enfoque-selectivo-de-salpicaduras-de-agua-zXQbf1pyZpo",
            ja: "水しぶきのセレクティブフォーカス撮影-zXQbf1pyZpo",
            fr: "photographie-selective-des-eclaboussures-deau-zXQbf1pyZpo",
            it: "fotografia-a-fuoco-selettiva-di-spruzzi-dacqua-zXQbf1pyZpo",
            ko: "물보라의-선택적-초점-촬영-zXQbf1pyZpo",
            de: "selektive-fokusfotografie-von-wasserspritzern-zXQbf1pyZpo",
            pt: "fotografia-de-foco-seletivo-de-respingo-de-agua-zXQbf1pyZpo",
            id: "fotografi-fokus-selektif-percikan-air-zXQbf1pyZpo",
        },
        created_at: "2019-07-12T21:14:31Z",
        updated_at: "2026-08-10T01:32:47Z",
        promoted_at: "2019-07-14T09:20:46Z",
        width: 4272,
        height: 2848,
        color: "#595940",
        blur_hash: "LHEeoD,BM|ni~AWCV@xFIVayxZ$$",
        description: null,
        breadcrumbs: [],
        urls: {
            raw: "https://images.unsplash.com/photo-1562966057-a7b0276b2b2d?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0",
            full: "https://images.unsplash.com/photo-1562966057-a7b0276b2b2d?crop=entropy&cs=srgb&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=85",
            regular:
                "https://images.unsplash.com/photo-1562966057-a7b0276b2b2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=1080",
            small: "https://images.unsplash.com/photo-1562966057-a7b0276b2b2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=400",
            thumb: "https://images.unsplash.com/photo-1562966057-a7b0276b2b2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=200",
            small_s3:
                "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1562966057-a7b0276b2b2d",
        },
        likes: 162,
        liked_by_user: false,
        bookmarked: false,
        current_user_collections: [],
        sponsorship: null,
        topic_submissions: {},
        asset_type: "photo",
        slug: "selective-focus-photography-of-splash-of-water-zXQbf1pyZpo",
        alt_description: "selective focus photography of splash of water",
        links: {
            self: "https://api.unsplash.com/photos/selective-focus-photography-of-splash-of-water-zXQbf1pyZpo",
            html: "https://unsplash.com/photos/selective-focus-photography-of-splash-of-water-zXQbf1pyZpo",
            download:
                "https://unsplash.com/photos/zXQbf1pyZpo/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
            download_location:
                "https://api.unsplash.com/photos/zXQbf1pyZpo/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
        },
        user: {
            id: "ViHm9qIikus",
            updated_at: "2026-07-10T14:01:37Z",
            username: "max010",
            name: "Danil Shostak",
            first_name: "Danil",
            last_name: "Shostak",
            twitter_username: "DanilShostak",
            portfolio_url: "https://pixabay.com/users/danil_shostak-12813905/",
            bio: "https://www.instagram.com/dan_shs/ \r\nhttps://pixabay.com/ru/users/danil_shostak-12813905/ https://www.pexels.com/@danil-shostak-1324124 https://www.facebook.com/danil.shostak1",
            location: null,
            links: {
                self: "https://api.unsplash.com/users/max010",
                photos: "https://api.unsplash.com/users/max010/photos",
                likes: "https://api.unsplash.com/users/max010/likes",
                html: "https://unsplash.com/@max010",
            },
            profile_image: {
                small: "https://images.unsplash.com/profile-1712412978609-bf2ea0cc4440image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
                medium: "https://images.unsplash.com/profile-1712412978609-bf2ea0cc4440image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
                large: "https://images.unsplash.com/profile-1712412978609-bf2ea0cc4440image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
            },
            instagram_username: "dan_shs",
            total_collections: 0,
            total_likes: 102,
            total_photos: 38,
            total_free_photos: 38,
            total_promoted_photos: 2,
            total_illustrations: 0,
            total_free_illustrations: 0,
            total_promoted_illustrations: 0,
            accepted_tos: true,
            for_hire: false,
            social: {
                instagram_username: "dan_shs",
                portfolio_url: "https://pixabay.com/users/danil_shostak-12813905/",
                twitter_username: "DanilShostak",
                paypal_email: null,
            },
        },
        exif: {
            make: "Canon",
            model: "Canon EOS DIGITAL REBEL XSi",
            name: "Canon, EOS DIGITAL REBEL XSi",
            exposure_time: "1/800",
            aperture: null,
            focal_length: null,
            iso: 400,
        },
        location: {
            name: null,
            city: null,
            country: null,
            position: {
                latitude: null,
                longitude: null,
            },
        },
        views: 40380514,
        downloads: 7899,
    },
    {
        id: "b3PuuRU8IPc",
        alternative_slugs: {
            en: "milky-way-photography-above-concrete-building-b3PuuRU8IPc",
            es: "fotografia-de-la-via-lactea-sobre-un-edificio-de-hormigon-b3PuuRU8IPc",
            ja: "コンクリートの建物の上の天の川写真-b3PuuRU8IPc",
            fr: "photographie-de-la-voie-lactee-au-dessus-dun-batiment-en-beton-b3PuuRU8IPc",
            it: "fotografia-della-via-lattea-sopra-ledificio-in-cemento-b3PuuRU8IPc",
            ko: "콘크리트-건물-위의-은하수-사진-b3PuuRU8IPc",
            de: "milchstrassenfotografie-uber-betongebaude-b3PuuRU8IPc",
            pt: "fotografia-da-via-lactea-acima-do-edificio-de-concreto-b3PuuRU8IPc",
            id: "fotografi-bima-sakti-di-atas-bangunan-beton-b3PuuRU8IPc",
        },
        created_at: "2018-07-09T22:59:21Z",
        updated_at: "2026-08-10T02:04:10Z",
        promoted_at: "2018-07-10T14:19:53Z",
        width: 4511,
        height: 3158,
        color: "#262626",
        blur_hash: "L57w87AA,.s=15aeI.oM0x=zNGR$",
        description:
            "The church is dedicated to St Thomas à Becket, the Archbishop of Canterbury from 1162 until his murder in 1170.\r\nThis iconic church has been used as a filming location, including 2011 BBC adaption of Great Expectations, Great Expectations (2012 film) and Parade’s End (TV series)",
        breadcrumbs: [],
        urls: {
            raw: "https://images.unsplash.com/photo-1531177071211-ed1b7991958b?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0",
            full: "https://images.unsplash.com/photo-1531177071211-ed1b7991958b?crop=entropy&cs=srgb&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=85",
            regular:
                "https://images.unsplash.com/photo-1531177071211-ed1b7991958b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=1080",
            small: "https://images.unsplash.com/photo-1531177071211-ed1b7991958b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=400",
            thumb: "https://images.unsplash.com/photo-1531177071211-ed1b7991958b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=200",
            small_s3:
                "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1531177071211-ed1b7991958b",
        },
        likes: 1088,
        liked_by_user: false,
        bookmarked: false,
        current_user_collections: [],
        sponsorship: null,
        topic_submissions: {
            wallpapers: {
                status: "approved",
                approved_on: "2021-11-25T15:54:04Z",
            },
            "architecture-interior": {
                status: "rejected",
            },
        },
        asset_type: "photo",
        slug: "milky-way-photography-above-concrete-building-b3PuuRU8IPc",
        alt_description: "Milky Way photography above concrete building",
        links: {
            self: "https://api.unsplash.com/photos/milky-way-photography-above-concrete-building-b3PuuRU8IPc",
            html: "https://unsplash.com/photos/milky-way-photography-above-concrete-building-b3PuuRU8IPc",
            download:
                "https://unsplash.com/photos/b3PuuRU8IPc/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
            download_location:
                "https://api.unsplash.com/photos/b3PuuRU8IPc/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
        },
        user: {
            id: "OhFUnBCq8o8",
            updated_at: "2026-07-10T13:50:52Z",
            username: "zoltantasi",
            name: "Zoltan Tasi",
            first_name: "Zoltan",
            last_name: "Tasi",
            twitter_username: null,
            portfolio_url: "https://foundation.app/@zoltan_tasi",
            bio: "Follow the light 🌞",
            location: "Planet Earth",
            links: {
                self: "https://api.unsplash.com/users/zoltantasi",
                photos: "https://api.unsplash.com/users/zoltantasi/photos",
                likes: "https://api.unsplash.com/users/zoltantasi/likes",
                html: "https://unsplash.com/@zoltantasi",
            },
            profile_image: {
                small: "https://images.unsplash.com/profile-fb-1487690559-aebd4d484d95.jpg?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
                medium: "https://images.unsplash.com/profile-fb-1487690559-aebd4d484d95.jpg?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
                large: "https://images.unsplash.com/profile-fb-1487690559-aebd4d484d95.jpg?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
            },
            instagram_username: "zoltan_tasi",
            total_collections: 16,
            total_likes: 3605,
            total_photos: 336,
            total_free_photos: 336,
            total_promoted_photos: 219,
            total_illustrations: 0,
            total_free_illustrations: 0,
            total_promoted_illustrations: 0,
            accepted_tos: true,
            for_hire: true,
            social: {
                instagram_username: "zoltan_tasi",
                portfolio_url: "https://foundation.app/@zoltan_tasi",
                twitter_username: null,
                paypal_email: null,
            },
        },
        exif: {
            make: "FUJIFILM",
            model: "X-T1",
            name: "FUJIFILM, X-T1",
            exposure_time: "220",
            aperture: "2.8",
            focal_length: "12.0",
            iso: 400,
        },
        location: {
            name: "Fairfield, United Kingdom",
            city: "Fairfield",
            country: "United Kingdom",
            position: {
                latitude: 51.0043933565262,
                longitude: 0.80184033071896,
            },
        },
        views: 26871486,
        downloads: 128563,
    },
    {
        id: "bCpAvL49GsU",
        alternative_slugs: {
            en: "aerial-photography-of-ocean-bCpAvL49GsU",
            es: "fotografia-aerea-del-oceano-bCpAvL49GsU",
            ja: "海の航空写真-bCpAvL49GsU",
            fr: "photographie-aerienne-de-locean-bCpAvL49GsU",
            it: "fotografia-aerea-delloceano-bCpAvL49GsU",
            ko: "바다의-항공-사진-bCpAvL49GsU",
            de: "luftaufnahmen-des-ozeans-bCpAvL49GsU",
            pt: "fotografia-aerea-do-oceano-bCpAvL49GsU",
            id: "fotografi-udara-laut-bCpAvL49GsU",
        },
        created_at: "2018-04-02T04:45:23Z",
        updated_at: "2026-08-10T00:07:21Z",
        promoted_at: "2018-04-03T02:36:25Z",
        width: 6720,
        height: 4480,
        color: "#0c2626",
        blur_hash: "LKCHA[m,Dhxv00tlxubbHrM{kBae",
        description: "An Easter retreat in NSW",
        breadcrumbs: [],
        urls: {
            raw: "https://images.unsplash.com/photo-1522643062452-f5b403123bdf?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0",
            full: "https://images.unsplash.com/photo-1522643062452-f5b403123bdf?crop=entropy&cs=srgb&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=85",
            regular:
                "https://images.unsplash.com/photo-1522643062452-f5b403123bdf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=1080",
            small: "https://images.unsplash.com/photo-1522643062452-f5b403123bdf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=400",
            thumb: "https://images.unsplash.com/photo-1522643062452-f5b403123bdf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=200",
            small_s3:
                "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1522643062452-f5b403123bdf",
        },
        likes: 446,
        liked_by_user: false,
        bookmarked: false,
        current_user_collections: [],
        sponsorship: null,
        topic_submissions: {
            wallpapers: {
                status: "approved",
                approved_on: "2020-11-20T12:47:17Z",
            },
        },
        asset_type: "photo",
        slug: "aerial-photography-of-ocean-bCpAvL49GsU",
        alt_description: "aerial photography of ocean",
        links: {
            self: "https://api.unsplash.com/photos/aerial-photography-of-ocean-bCpAvL49GsU",
            html: "https://unsplash.com/photos/aerial-photography-of-ocean-bCpAvL49GsU",
            download:
                "https://unsplash.com/photos/bCpAvL49GsU/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
            download_location:
                "https://api.unsplash.com/photos/bCpAvL49GsU/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
        },
        user: {
            id: "Gy8ln6vNHwA",
            updated_at: "2026-07-10T13:52:40Z",
            username: "jamie_davies",
            name: "Jamie Davies",
            first_name: "Jamie",
            last_name: "Davies",
            twitter_username: null,
            portfolio_url: null,
            bio: "Canon 5D MrkIV",
            location: "London, UK",
            links: {
                self: "https://api.unsplash.com/users/jamie_davies",
                photos: "https://api.unsplash.com/users/jamie_davies/photos",
                likes: "https://api.unsplash.com/users/jamie_davies/likes",
                html: "https://unsplash.com/@jamie_davies",
            },
            profile_image: {
                small: "https://images.unsplash.com/profile-1511077820971-adc6ddc5030b?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
                medium: "https://images.unsplash.com/profile-1511077820971-adc6ddc5030b?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
                large: "https://images.unsplash.com/profile-1511077820971-adc6ddc5030b?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
            },
            instagram_username: "jamm_d",
            total_collections: 11,
            total_likes: 112,
            total_photos: 73,
            total_free_photos: 73,
            total_promoted_photos: 23,
            total_illustrations: 0,
            total_free_illustrations: 0,
            total_promoted_illustrations: 0,
            accepted_tos: true,
            for_hire: true,
            social: {
                instagram_username: "jamm_d",
                portfolio_url: null,
                twitter_username: null,
                paypal_email: null,
            },
        },
        exif: {
            make: "Canon",
            model: "Canon EOS 5D Mark IV",
            name: "Canon, EOS 5D Mark IV",
            exposure_time: "1/2000",
            aperture: "4.0",
            focal_length: "50.0",
            iso: 100,
        },
        location: {
            name: "Dee Why Head, North Curl Curl, Australia",
            city: "North Curl Curl",
            country: "Australia",
            position: {
                latitude: -33.7673021,
                longitude: 151.3017792,
            },
        },
        views: 17242819,
        downloads: 26316,
    },
    {
        id: "-8FERkBXv-Y",
        alternative_slugs: {
            en: "a-snowy-landscape-with-trees--8FERkBXv-Y",
            es: "un-paisaje-nevado-con-arboles--8FERkBXv-Y",
            ja: "木々のある雪景色--8FERkBXv-Y",
            fr: "un-paysage-enneige-avec-des-arbres--8FERkBXv-Y",
            it: "un-paesaggio-innevato-con-alberi--8FERkBXv-Y",
            ko: "나무가있는-눈-덮인-풍경--8FERkBXv-Y",
            de: "eine-verschneite-landschaft-mit-baumen--8FERkBXv-Y",
            pt: "uma-paisagem-nevada-com-arvores--8FERkBXv-Y",
            id: "lanskap-bersalju-dengan-pepohonan--8FERkBXv-Y",
        },
        created_at: "2022-03-29T10:02:27Z",
        updated_at: "2026-08-10T02:04:01Z",
        promoted_at: "2022-03-31T01:00:01Z",
        width: 6000,
        height: 4000,
        color: "#737373",
        blur_hash: "L9ECUtMy4nxC~pD+adsRX;Nanhe.",
        description: null,
        breadcrumbs: [],
        urls: {
            raw: "https://images.unsplash.com/photo-1648547415024-b8b03547e78c?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0",
            full: "https://images.unsplash.com/photo-1648547415024-b8b03547e78c?crop=entropy&cs=srgb&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=85",
            regular:
                "https://images.unsplash.com/photo-1648547415024-b8b03547e78c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=1080",
            small: "https://images.unsplash.com/photo-1648547415024-b8b03547e78c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=400",
            thumb: "https://images.unsplash.com/photo-1648547415024-b8b03547e78c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA&ixlib=rb-4.1.0&q=80&w=200",
            small_s3:
                "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1648547415024-b8b03547e78c",
        },
        likes: 171,
        liked_by_user: false,
        bookmarked: false,
        current_user_collections: [],
        sponsorship: null,
        topic_submissions: {},
        asset_type: "photo",
        slug: "a-snowy-landscape-with-trees--8FERkBXv-Y",
        alt_description: "a snowy landscape with trees",
        links: {
            self: "https://api.unsplash.com/photos/a-snowy-landscape-with-trees--8FERkBXv-Y",
            html: "https://unsplash.com/photos/a-snowy-landscape-with-trees--8FERkBXv-Y",
            download:
                "https://unsplash.com/photos/-8FERkBXv-Y/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
            download_location:
                "https://api.unsplash.com/photos/-8FERkBXv-Y/download?ixid=M3wxMDIyOTE2fDB8MXxyYW5kb218fHx8fHx8fHwxNzg2MzM5Mjk1fA",
        },
        user: {
            id: "E-RU4BXzBGM",
            updated_at: "2026-07-10T14:06:35Z",
            username: "koloshots",
            name: "Alex Kolodziej",
            first_name: "Alex",
            last_name: "Kolodziej",
            twitter_username: null,
            portfolio_url: "https://www.koloshots.com",
            bio: "↠ᴍᴏᴏᴅʏ ᴘʜᴏᴛᴏɢʀᴀᴘʜʏ 📷\r\n↠ғʀᴇɪʙᴜʀɢ ɪᴍ ʙʀᴇɪsɢᴀᴜ 🇩🇪  ↠ʙʟᴀᴄᴋ ғᴏʀᴇsᴛ 🌲🏕🌳  ↠ᴄᴀᴍ: sᴏɴʏ ᴀʟᴘʜᴀ 7ᴍ2",
            location: "Freiburg im Breisgau",
            links: {
                self: "https://api.unsplash.com/users/koloshots",
                photos: "https://api.unsplash.com/users/koloshots/photos",
                likes: "https://api.unsplash.com/users/koloshots/likes",
                html: "https://unsplash.com/@koloshots",
            },
            profile_image: {
                small: "https://images.unsplash.com/profile-1648547036861-c3be5b3e7841image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
                medium: "https://images.unsplash.com/profile-1648547036861-c3be5b3e7841image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
                large: "https://images.unsplash.com/profile-1648547036861-c3be5b3e7841image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
            },
            instagram_username: "koloshots",
            total_collections: 2,
            total_likes: 36,
            total_photos: 121,
            total_free_photos: 121,
            total_promoted_photos: 13,
            total_illustrations: 0,
            total_free_illustrations: 0,
            total_promoted_illustrations: 0,
            accepted_tos: true,
            for_hire: true,
            social: {
                instagram_username: "koloshots",
                portfolio_url: "https://www.koloshots.com",
                twitter_username: null,
                paypal_email: null,
            },
        },
        exif: {
            make: "SONY",
            model: "ILCE-7M2",
            name: "SONY, ILCE-7M2",
            exposure_time: "1/100",
            aperture: "8.0",
            focal_length: "42.0",
            iso: 100,
        },
        location: {
            name: null,
            city: null,
            country: null,
            position: {
                latitude: null,
                longitude: null,
            },
        },
        views: 16723202,
        downloads: 84382,
    },
];
